from __future__ import annotations
from sqlalchemy import Column, Integer, String, Text, DateTime, Boolean, Float, ForeignKey, UniqueConstraint, Index
from sqlalchemy.orm import relationship
from sqlalchemy.types import JSON
from sqlalchemy.sql import func
from .db import Base

class Opportunity(Base):
    __tablename__ = "opportunities"
    id = Column(Integer, primary_key=True)
    case_name = Column(String(300), nullable=False, index=True)
    normalized_key = Column(String(500), nullable=False, unique=True, index=True)
    trigger_type = Column(String(120), default="New Lawsuit", index=True)
    case_type = Column(String(120), default="Unknown", index=True)
    matter_type = Column(String(160), default="", index=True)
    trigger_category = Column(String(160), default="", index=True)
    status = Column(String(50), default="New", index=True)
    parties = Column(JSON, default=list)
    party_roles = Column(JSON, default=dict)
    law_firms = Column(JSON, default=list)
    court_or_regulator = Column(String(300), default="")
    jurisdiction = Column(String(160), default="")
    summary = Column(Text, default="")
    factual_basis = Column(Text, default="")
    discovery_pain_summary = Column(Text, default="")
    why_now = Column(Text, default="")
    why_decoverai = Column(Text, default="")
    recommended_personas = Column(JSON, default=list)
    sales_angle_one_liner = Column(Text, default="")
    email_subject = Column(String(300), default="")
    email_body = Column(Text, default="")
    linkedin_message = Column(Text, default="")
    call_opener = Column(Text, default="")
    recommended_persona = Column(String(200), default="")
    pitch_angle = Column(Text, default="")
    generated_email = Column(Text, default="")
    notes = Column(Text, default="")
    score = Column(Float, default=0, index=True)
    confidence_score = Column(Float, default=0, index=True)
    source_quality_score = Column(Float, default=0)
    discovery_pain_score = Column(Float, default=0, index=True)
    dcover_fit_score = Column(Float, default=0, index=True)
    sales_actionability_score = Column(Float, default=0)
    final_trigger_score = Column(Float, default=0, index=True)
    extraction_warnings = Column(JSON, default=list)
    missing_fields = Column(JSON, default=list)
    is_litigation_trigger = Column(Boolean, default=False)
    trigger_relevance_reason = Column(Text, default="")
    gate_status = Column(String(40), default="failed")
    gate_failure_reasons = Column(JSON, default=list)
    duplicate_confidence = Column(Float, default=0)
    discovery_burden_score = Column(Float, default=0)
    urgency_score = Column(Float, default=0)
    decoverAI_fit_score = Column(Float, default=0)
    company_size_score = Column(Float, default=0)
    law_firm_signal_score = Column(Float, default=0)
    freshness_score = Column(Float, default=0)
    case_type_score = Column(Float, default=0)
    scoring_breakdown = Column(JSON, default=dict)
    enrichment_status = Column(String(50), default="pending")
    created_at = Column(DateTime(timezone=True), server_default=func.now(), index=True)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), index=True)

    evidence = relationship("SourceEvidence", cascade="all,delete", back_populates="opportunity")
    enriched_accounts = relationship("EnrichedAccount", cascade="all,delete", back_populates="opportunity")
    research_tasks = relationship("ResearchTask", cascade="all,delete", back_populates="opportunity")
    activities = relationship("OpportunityActivity", cascade="all,delete", back_populates="opportunity")

Index("ix_opportunity_status_score", Opportunity.status, Opportunity.score)
Index("ix_opportunity_daily_triggers", Opportunity.final_trigger_score, Opportunity.status, Opportunity.matter_type)

class SourceEvidence(Base):
    __tablename__ = "source_evidence"
    id = Column(Integer, primary_key=True)
    opportunity_id = Column(Integer, ForeignKey("opportunities.id", ondelete="CASCADE"), index=True)
    source_url = Column(Text, nullable=False)
    source_title = Column(String(500), default="")
    publisher = Column(String(200), default="")
    published_at = Column(DateTime(timezone=True), nullable=True)
    snippet = Column(Text, default="")
    evidence_type = Column(String(80), default="legal_news")
    credibility_score = Column(Float, default=70)
    source_tier = Column(String(80), default="low_quality", index=True)
    source_reason = Column(Text, default="")
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    opportunity = relationship("Opportunity", back_populates="evidence")

class EnrichedAccount(Base):
    __tablename__ = "enriched_accounts"
    id = Column(Integer, primary_key=True)
    opportunity_id = Column(Integer, ForeignKey("opportunities.id", ondelete="CASCADE"), index=True)
    entity_name = Column(String(300), nullable=False)
    entity_type = Column(String(50), default="unknown")
    website = Column(String(300), default="")
    industry = Column(String(120), default="")
    company_size_band = Column(String(120), default="Unknown")
    geography = Column(String(120), default="Unknown")
    description = Column(Text, default="")
    likely_data_sources = Column(JSON, default=list)
    legal_team_signal = Column(Text, default="")
    enrichment_status = Column(String(50), default="enriched")
    confidence_score = Column(Float, default=70)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())
    opportunity = relationship("Opportunity", back_populates="enriched_accounts")
    contacts = relationship("SuggestedContact", cascade="all,delete", back_populates="account")

class SuggestedContact(Base):
    __tablename__ = "suggested_contacts"
    id = Column(Integer, primary_key=True)
    opportunity_id = Column(Integer, ForeignKey("opportunities.id", ondelete="CASCADE"), index=True)
    account_id = Column(Integer, ForeignKey("enriched_accounts.id", ondelete="CASCADE"), index=True)
    persona = Column(String(160), nullable=False)
    title_keywords = Column(JSON, default=list)
    why_relevant = Column(Text, default="")
    outreach_priority = Column(Integer, default=2)
    confidence_score = Column(Float, default=70)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    account = relationship("EnrichedAccount", back_populates="contacts")

class ScoringConfig(Base):
    __tablename__ = "scoring_config"
    id = Column(Integer, primary_key=True)
    name = Column(String(120), default="Default")
    is_active = Column(Boolean, default=True, index=True)
    case_type_weight = Column(Float, default=20)
    discovery_burden_weight = Column(Float, default=25)
    company_size_weight = Column(Float, default=15)
    urgency_weight = Column(Float, default=15)
    law_firm_signal_weight = Column(Float, default=10)
    freshness_weight = Column(Float, default=5)
    decoverAI_fit_weight = Column(Float, default=10)
    confidence_weight = Column(Float, default=20)
    source_quality_weight = Column(Float, default=20)
    discovery_pain_quality_weight = Column(Float, default=25)
    dcover_fit_weight = Column(Float, default=25)
    sales_actionability_weight = Column(Float, default=10)
    final_trigger_threshold = Column(Float, default=70)
    min_confidence_score = Column(Float, default=60)
    min_source_quality_score = Column(Float, default=50)
    min_discovery_pain_score = Column(Float, default=55)
    min_dcover_fit_score = Column(Float, default=55)
    min_sales_actionability_score = Column(Float, default=60)
    max_daily_triggers = Column(Integer, default=50)
    default_geography = Column(String(120), default="US")
    default_industry = Column(String(160), default="technology")
    default_time_range = Column(String(40), default="week")
    default_max_results = Column(Integer, default=40)
    max_signal_age_days = Column(Integer, default=90)
    allow_unknown_signal_date = Column(Boolean, default=False)
    max_per_source_domain = Column(Integer, default=4)
    max_per_trigger_category = Column(Integer, default=5)
    max_per_same_party = Column(Integer, default=2)
    source_allowlist = Column(Text, default="")
    source_blocklist = Column(Text, default="")
    discovery_query_settings = Column(JSON, default=dict)
    source_packs = Column(JSON, default=list)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

class ResearchTask(Base):
    __tablename__ = "research_tasks"
    id = Column(Integer, primary_key=True)
    opportunity_id = Column(Integer, ForeignKey("opportunities.id", ondelete="CASCADE"), index=True)
    task_type = Column(String(120), nullable=False)
    status = Column(String(50), default="pending")
    input_payload = Column(JSON, default=dict)
    output_payload = Column(JSON, default=dict)
    error_message = Column(Text, default="")
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())
    opportunity = relationship("Opportunity", back_populates="research_tasks")

class Campaign(Base):
    __tablename__ = "campaigns"
    id = Column(Integer, primary_key=True)
    name = Column(String(180), nullable=False, unique=True)
    description = Column(Text, default="")
    target_segment = Column(String(200), default="")
    owner_name = Column(String(120), default="Sales")
    status = Column(String(50), default="active")
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())
    opportunities = relationship("CampaignOpportunity", cascade="all,delete", back_populates="campaign")

class CampaignOpportunity(Base):
    __tablename__ = "campaign_opportunities"
    campaign_id = Column(Integer, ForeignKey("campaigns.id", ondelete="CASCADE"), primary_key=True)
    opportunity_id = Column(Integer, ForeignKey("opportunities.id", ondelete="CASCADE"), primary_key=True, index=True)
    added_at = Column(DateTime(timezone=True), server_default=func.now())
    campaign = relationship("Campaign", back_populates="opportunities")
    opportunity = relationship("Opportunity")

class SavedView(Base):
    __tablename__ = "saved_views"
    id = Column(Integer, primary_key=True)
    name = Column(String(160), nullable=False, unique=True)
    filters = Column(JSON, default=dict)
    sort = Column(JSON, default=dict)
    is_default = Column(Boolean, default=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

class OpportunityActivity(Base):
    __tablename__ = "opportunity_activity"
    id = Column(Integer, primary_key=True)
    opportunity_id = Column(Integer, ForeignKey("opportunities.id", ondelete="CASCADE"), index=True)
    actor_name = Column(String(120), default="System")
    activity_type = Column(String(100), nullable=False)
    message = Column(Text, nullable=False)
    metadata_json = Column(JSON, default=dict)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), index=True)
    opportunity = relationship("Opportunity", back_populates="activities")

class WebDiscoveryRun(Base):
    __tablename__ = "web_discovery_runs"
    id = Column(Integer, primary_key=True)
    query = Column(Text, nullable=False, default="")
    trigger_type = Column(String(120), nullable=False, index=True)
    geography = Column(String(120), default="")
    industry = Column(String(160), default="")
    time_range = Column(String(40), default="week")
    status = Column(String(40), default="pending", index=True)
    total_results = Column(Integer, default=0)
    converted_count = Column(Integer, default=0)
    error_message = Column(Text, default="")
    created_at = Column(DateTime(timezone=True), server_default=func.now(), index=True)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), index=True)
    signals = relationship("DiscoveredSignal", cascade="all,delete", back_populates="discovery_run")

class DiscoveredSignal(Base):
    __tablename__ = "discovered_signals"
    id = Column(Integer, primary_key=True)
    discovery_run_id = Column(Integer, ForeignKey("web_discovery_runs.id", ondelete="CASCADE"), index=True)
    title = Column(String(500), nullable=False)
    source_url = Column(Text, nullable=False, index=True)
    source_domain = Column(String(240), default="", index=True)
    publisher = Column(String(240), default="")
    published_at = Column(DateTime(timezone=True), nullable=True)
    signal_date = Column(DateTime(timezone=True), nullable=True, index=True)
    signal_age_days = Column(Integer, nullable=True, index=True)
    freshness_status = Column(String(40), default="unknown", index=True)
    freshness_reason = Column(Text, default="")
    source_tier = Column(String(80), default="low_quality", index=True)
    source_reason = Column(Text, default="")
    raw_snippet = Column(Text, default="")
    scraped_text = Column(Text, default="")
    trigger_type = Column(String(120), default="", index=True)
    case_type = Column(String(160), default="")
    matter_type = Column(String(160), default="", index=True)
    trigger_category = Column(String(160), default="", index=True)
    parties = Column(JSON, default=list)
    party_roles = Column(JSON, default=dict)
    law_firms = Column(JSON, default=list)
    courts = Column(JSON, default=list)
    regulators = Column(JSON, default=list)
    court_or_regulator = Column(String(300), default="")
    jurisdiction = Column(String(160), default="")
    summary = Column(Text, default="")
    factual_basis = Column(Text, default="")
    discovery_pain_summary = Column(Text, default="")
    why_now = Column(Text, default="")
    why_decoverai = Column(Text, default="")
    why_relevant_to_decoverAI = Column(Text, default="")
    recommended_personas = Column(JSON, default=list)
    sales_angle_one_liner = Column(Text, default="")
    email_subject = Column(String(300), default="")
    email_body = Column(Text, default="")
    linkedin_message = Column(Text, default="")
    call_opener = Column(Text, default="")
    sales_action_plan = Column(JSON, default=dict)
    sales_review_status = Column(String(40), default="", index=True)
    sales_review_reason = Column(String(80), default="", index=True)
    sales_review_notes = Column(Text, default="")
    discovery_burden_score = Column(Float, default=0)
    urgency_score = Column(Float, default=0)
    decover_fit_score = Column(Float, default=0)
    confidence_score = Column(Float, default=0)
    source_quality_score = Column(Float, default=0, index=True)
    discovery_pain_score = Column(Float, default=0, index=True)
    dcover_fit_score = Column(Float, default=0, index=True)
    sales_actionability_score = Column(Float, default=0)
    final_trigger_score = Column(Float, default=0, index=True)
    extraction_warnings = Column(JSON, default=list)
    missing_fields = Column(JSON, default=list)
    is_litigation_trigger = Column(Boolean, default=False, index=True)
    trigger_relevance_reason = Column(Text, default="")
    gate_status = Column(String(40), default="failed", index=True)
    gate_failure_reasons = Column(JSON, default=list)
    duplicate_confidence = Column(Float, default=0)
    gate_passed = Column(Boolean, default=False, index=True)
    gate_reason = Column(Text, default="")
    rejection_reason = Column(Text, default="")
    duplicate_reason = Column(Text, default="")
    duplicate_of_opportunity_id = Column(Integer, ForeignKey("opportunities.id", ondelete="SET NULL"), nullable=True, index=True)
    status = Column(String(40), default="new", index=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), index=True)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), index=True)
    discovery_run = relationship("WebDiscoveryRun", back_populates="signals")
    scrape_attempts = relationship("ScrapeAttempt", cascade="all,delete", back_populates="discovered_signal")
    duplicate_of_opportunity = relationship("Opportunity")

    @property
    def scraped_text_preview(self):
        return (self.scraped_text or "")[:1200]

Index("ix_discovered_signal_run_status", DiscoveredSignal.discovery_run_id, DiscoveredSignal.status)
Index("ix_discovered_signal_quality", DiscoveredSignal.final_trigger_score, DiscoveredSignal.status, DiscoveredSignal.gate_passed)
Index("ix_discovered_signal_matter_trigger", DiscoveredSignal.matter_type, DiscoveredSignal.trigger_category)

class ScrapeAttempt(Base):
    __tablename__ = "scrape_attempts"
    id = Column(Integer, primary_key=True)
    discovered_signal_id = Column(Integer, ForeignKey("discovered_signals.id", ondelete="CASCADE"), index=True)
    provider = Column(String(80), nullable=False)
    status = Column(String(40), nullable=False)
    http_status = Column(Integer, nullable=True)
    error_message = Column(Text, default="")
    robots_allowed = Column(Boolean, default=False)
    duration_ms = Column(Integer, default=0)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), index=True)
    discovered_signal = relationship("DiscoveredSignal", back_populates="scrape_attempts")
